CREATE TABLE [TbNoticia](
	[NotCodigo] [int] IDENTITY(1,1) NOT NULL,
	[NotTitulo] [varchar](50) NOT NULL,
	[NotTexto] [text] NULL,
	[NotUltimaAtualizacao] [datetime] NOT NULL,
 CONSTRAINT [PK_TbNoticia] PRIMARY KEY CLUSTERED 
(
	[NotCodigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
